create table BlogContent (
id_Content int auto_increment not null primary key,
title varchar(400) not null,
intro text not null,
content text not null,
authorId int,
numOfComments int default 0,
date DATETIME,
foreign key (authorId) references SiteUsers(id)
ON DELETE CASCADE ON UPDATE CASCADE );

create table BlogComments (
id_Comment int auto_increment not null primary key,
contentId int,
title_Comment varchar(100),
content_Comment text,
author_Comment varchar(100),
date_Comment DATETIME,
foreign key (contentId) references BlogContent(id)
ON DELETE CASCADE ON UPDATE CASCADE );

insert into BlogContent(title, intro, content, authorId, numOfComments, date)
values ("Lorem Dolor", "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vel lacus eros. Maecenas tristique lectus nec augue semper sed elementum lorem pretium. </p>", "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lorem leo, ultricies ac blandit faucibus, tempor et lectus. Donec non arcu vitae turpis laoreet semper ut vitae risus. Morbi fermentum ligula sit amet risus aliquet tincidunt. Etiam id nibh urna, at consectetur purus. Integer volutpat sagittis leo, ac tristique velit tempor eleifend. Ut purus metus, rhoncus a tristique quis, malesuada eu lectus. Nullam felis sapien, lobortis sed commodo a, suscipit at neque. Integer in elit libero. Nullam quis tincidunt purus. Nam ultrices metus quis nisi lacinia vehicula. Aliquam dolor erat, porttitor eget luctus in, malesuada id elit. Aliquam dictum, metus eu aliquet semper, dolor justo gravida felis, sit amet interdum ante ligula a nisi. Curabitur nec velit et turpis hendrerit fermentum non ut odio. Nunc massa sapien, hendrerit id convallis nec, consequat sollicitudin sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce vestibulum facilisis placerat. Aliquam quam lectus, luctus non facilisis ac, pretium vitae sapien. Etiam iaculis libero vitae eros mollis pharetra pellentesque felis aliquam. Mauris posuere dictum nisi, sit amet laoreet eros euismod eget. Curabitur nisi justo, tristique eu scelerisque et, luctus sit amet nulla. Mauris sed diam quis purus elementum aliquam nec non enim. Cras dignissim, urna vitae rhoncus auctor, tortor ipsum vehicula libero, et ornare est dui ut justo. In vehicula ultricies dolor, ut convallis quam scelerisque at. Ut pellentesque augue vel nunc sodales et convallis erat blandit. Ut pulvinar semper lorem, quis mattis erat fermentum non. Pellentesque et justo orci, eget accumsan est. Suspendisse potenti. Nunc tincidunt varius mattis. </p><p>Quisque erat ligula, iaculis vitae sollicitudin at, commodo quis massa. Proin eu congue est. Ut vel lacus auctor elit congue luctus. Aliquam sit amet lorem sed ligula lacinia suscipit. Curabitur a est et dolor euismod ornare. Pellentesque tempus velit in tortor placerat et ultrices metus pretium. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur aliquam, lacus sed pulvinar suscipit, mi tortor dignissim diam, ac egestas purus lacus a augue. Donec in ligula vel leo iaculis porta at vitae enim. Suspendisse sagittis ultrices pharetra.</p>", 2, 3, "2010-01-03 08:02:32"),
       ("Ipsum Sit Amet", "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vel lacus eros. Maecenas tristique lectus nec augue semper sed elementum lorem pretium. </p>", "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lorem leo, ultricies ac blandit faucibus, tempor et lectus. Donec non arcu vitae turpis laoreet semper ut vitae risus. Morbi fermentum ligula sit amet risus aliquet tincidunt. Etiam id nibh urna, at consectetur purus. Integer volutpat sagittis leo, ac tristique velit tempor eleifend. Ut purus metus, rhoncus a tristique quis, malesuada eu lectus. Nullam felis sapien, lobortis sed commodo a, suscipit at neque. Integer in elit libero. Nullam quis tincidunt purus. Nam ultrices metus quis nisi lacinia vehicula. Aliquam dolor erat, porttitor eget luctus in, malesuada id elit. Aliquam dictum, metus eu aliquet semper, dolor justo gravida felis, sit amet interdum ante ligula a nisi. Curabitur nec velit et turpis hendrerit fermentum non ut odio. Nunc massa sapien, hendrerit id convallis nec, consequat sollicitudin sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce vestibulum facilisis placerat. Aliquam quam lectus, luctus non facilisis ac, pretium vitae sapien. Etiam iaculis libero vitae eros mollis pharetra pellentesque felis aliquam. Mauris posuere dictum nisi, sit amet laoreet eros euismod eget. Curabitur nisi justo, tristique eu scelerisque et, luctus sit amet nulla. Mauris sed diam quis purus elementum aliquam nec non enim. Cras dignissim, urna vitae rhoncus auctor, tortor ipsum vehicula libero, et ornare est dui ut justo. In vehicula ultricies dolor, ut convallis quam scelerisque at. Ut pellentesque augue vel nunc sodales et convallis erat blandit. Ut pulvinar semper lorem, quis mattis erat fermentum non. Pellentesque et justo orci, eget accumsan est. Suspendisse potenti. Nunc tincidunt varius mattis. </p><p>Quisque erat ligula, iaculis vitae sollicitudin at, commodo quis massa. Proin eu congue est. Ut vel lacus auctor elit congue luctus. Aliquam sit amet lorem sed ligula lacinia suscipit. Curabitur a est et dolor euismod ornare. Pellentesque tempus velit in tortor placerat et ultrices metus pretium. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur aliquam, lacus sed pulvinar suscipit, mi tortor dignissim diam, ac egestas purus lacus a augue. Donec in ligula vel leo iaculis porta at vitae enim. Suspendisse sagittis ultrices pharetra.</p>", 3, 1, "2010-01-03 18:02:32"),
       ("Duis Vel Lacus", "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vel lacus eros. Maecenas tristique lectus nec augue semper sed elementum lorem pretium. </p>", "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lorem leo, ultricies ac blandit faucibus, tempor et lectus. Donec non arcu vitae turpis laoreet semper ut vitae risus. Morbi fermentum ligula sit amet risus aliquet tincidunt. Etiam id nibh urna, at consectetur purus. Integer volutpat sagittis leo, ac tristique velit tempor eleifend. Ut purus metus, rhoncus a tristique quis, malesuada eu lectus. Nullam felis sapien, lobortis sed commodo a, suscipit at neque. Integer in elit libero. Nullam quis tincidunt purus. Nam ultrices metus quis nisi lacinia vehicula. Aliquam dolor erat, porttitor eget luctus in, malesuada id elit. Aliquam dictum, metus eu aliquet semper, dolor justo gravida felis, sit amet interdum ante ligula a nisi. Curabitur nec velit et turpis hendrerit fermentum non ut odio. Nunc massa sapien, hendrerit id convallis nec, consequat sollicitudin sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce vestibulum facilisis placerat. Aliquam quam lectus, luctus non facilisis ac, pretium vitae sapien. Etiam iaculis libero vitae eros mollis pharetra pellentesque felis aliquam. Mauris posuere dictum nisi, sit amet laoreet eros euismod eget. Curabitur nisi justo, tristique eu scelerisque et, luctus sit amet nulla. Mauris sed diam quis purus elementum aliquam nec non enim. Cras dignissim, urna vitae rhoncus auctor, tortor ipsum vehicula libero, et ornare est dui ut justo. In vehicula ultricies dolor, ut convallis quam scelerisque at. Ut pellentesque augue vel nunc sodales et convallis erat blandit. Ut pulvinar semper lorem, quis mattis erat fermentum non. Pellentesque et justo orci, eget accumsan est. Suspendisse potenti. Nunc tincidunt varius mattis. </p><p>Quisque erat ligula, iaculis vitae sollicitudin at, commodo quis massa. Proin eu congue est. Ut vel lacus auctor elit congue luctus. Aliquam sit amet lorem sed ligula lacinia suscipit. Curabitur a est et dolor euismod ornare. Pellentesque tempus velit in tortor placerat et ultrices metus pretium. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur aliquam, lacus sed pulvinar suscipit, mi tortor dignissim diam, ac egestas purus lacus a augue. Donec in ligula vel leo iaculis porta at vitae enim. Suspendisse sagittis ultrices pharetra.</p>", 4, 2, "2010-01-04 03:02:32");

insert into BlogComments(contentId, title_Comment, content_Comment, author_Comment, date_Comment)
values (1, "Nice thoughts", "I really appreciate your thoughts on this subject. They made me think. Thank you for that", "Grateful Steve", NOW()),
       (1, "You couldn't be wrong more", "I really just can't belive anyone has such ideas. It's scary!", "Honest Reader", NOW()),
       (2, "Very interesting", "Thanks for the interesting thoughts.", "John", NOW()),
       (1, "Another view", "I must disagree with the previous comment and in the same time agree with the first one.", "Hellen", NOW()),
       (3, "Straight to the point", "Thank you for expressing your thoughts so straight to the point. I do appreciate it and I'm sure others do too.", "Sally", NOW()),
       (3, "Really good reading", "Thank you for this post. It made an excellent reading!", "Tom", NOW());